from PyQt6.QtCore import QObject, pyqtSignal

class LanguageManager(QObject):
    language_changed = pyqtSignal(str)
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(LanguageManager, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if self._initialized: return
        super().__init__()
        self.current_language = "en"
        self.translations = {
            "en": {
                "dashboard": "Dashboard",
                "account": "Account Details",
                "wallet": "Wallet",
                "transfer": "Money Transfer",
                "notifications": "Notifications",
                "settings": "Settings",
                "logout": "Logout",
                "welcome_back": "Welcome back,",
                "manage_finances": "Manage your finances securely with Đăng Khoa Bank",
                "total_balance": "Total Balance",
                "monthly_income": "Monthly Income",
                "monthly_expense": "Monthly Expense",
                "total_savings": "Total Savings",
                "recent_transactions": "Recent Transactions",
                "quick_actions": "Quick Actions",
                "savings_progress": "Savings Progress",
                "virtual_cards": "Virtual Banking Cards",
                "available_balance": "Available Balance",
                "payment_qr": "Personal Payment QR",
                "trans_history": "Wallet Transaction History",
                "outgoing_trans": "Recent Outgoing Transfers",
                "membership": "Customer Membership",
                "benefits": "Member Benefits:",
                "banking_info": "Banking Information",
                "personal_info": "Personal Information",
                "edit_profile": "Edit Profile",
                "full_name": "Full Name",
                "username": "Username",
                "phone": "Phone Number",
                "cccd": "CCCD / Citizen ID",
                "email": "Email Address",
                "appearance": "Appearance",
                "theme_mode": "Theme Mode",
                "dark_mode": "Dark Mode",
                "light_mode": "Light Mode",
                "language": "Language",
                "account_settings": "Account",
                "change_password": "Change Password",
                "phone_payment_id": "Phone Payment ID",
                "acc_number": "Account Number",
                "bank_name": "Bank Name",
                "branch": "Branch",
                "member_since": "Member Since",
                "transfer_money": "Transfer Money",
                "add_wallet": "Add Wallet",
                "view_bills": "View Bills",
                "create_savings": "Create Savings",
                "priority_support": "Priority Support",
                "high_limits": "High Transfer Limits",
                "unlimited_limits": "Unlimited Limits",
                "standard_limits": "Standard Limits",
                "digital_support": "24/7 Digital Support",
                "elite_support": "Priority 24/7 Elite Support",
                "no_alerts": "No recent alerts.",
                "no_savings": "No active saving goals.",
                "download_qr": "Download Payment QR",
                "upload_qr": "Upload Payment QR",
                "select_qr": "Select QR Image from Device",
                "qr_decoded": "QR Decoded Successfully",
                "qr_invalid": "This QR code does not contain valid payment information.",
                "qr_error": "Unable to read payment QR.",
                "login": "Login",
                "register": "Register",
                "create_account": "Create Account",
                "password": "Password",
                "remember_me": "Remember Me",
                "forgot_password": "Forgot Password?",
                "access_premium": "Access your premium account",
                "modern_platform": "Modern Digital Banking Platform",
                "login_successful": "Login successful",
                "invalid_credentials": "Invalid username or password.",
                "required_fields": "Please enter all required fields."
            },
            "vi": {
                "dashboard": "Bảng điều khiển",
                "account": "Thông tin tài khoản",
                "wallet": "Ví của tôi",
                "transfer": "Chuyển tiền",
                "notifications": "Thông báo",
                "settings": "Cài đặt",
                "logout": "Đăng xuất",
                "welcome_back": "Chào mừng trở lại,",
                "manage_finances": "Quản lý tài chính an toàn với Đăng Khoa Bank",
                "total_balance": "Tổng số dư",
                "monthly_income": "Thu nhập tháng",
                "monthly_expense": "Chi tiêu tháng",
                "total_savings": "Tổng tiết kiệm",
                "recent_transactions": "Giao dịch gần đây",
                "quick_actions": "Thao tác nhanh",
                "savings_progress": "Tiến độ tiết kiệm",
                "virtual_cards": "Thẻ ngân hàng ảo",
                "available_balance": "Số dư khả dụng",
                "payment_qr": "Mã QR thanh toán",
                "trans_history": "Lịch sử giao dịch ví",
                "outgoing_trans": "Giao dịch chuyển tiền gần đây",
                "membership": "Hạng thành viên",
                "benefits": "Quyền lợi thành viên:",
                "banking_info": "Thông tin ngân hàng",
                "personal_info": "Thông tin cá nhân",
                "edit_profile": "Chỉnh sửa hồ sơ",
                "full_name": "Họ và tên",
                "username": "Tên đăng nhập",
                "phone": "Số điện thoại",
                "cccd": "CCCD / CMND",
                "email": "Địa chỉ Email",
                "appearance": "Giao diện",
                "theme_mode": "Chế độ nền",
                "dark_mode": "Nền tối",
                "light_mode": "Nền sáng",
                "language": "Ngôn ngữ",
                "account_settings": "Tài khoản",
                "change_password": "Đổi mật khẩu",
                "phone_payment_id": "ID thanh toán SĐT",
                "acc_number": "Số tài khoản",
                "bank_name": "Ngân hàng",
                "branch": "Chi nhánh",
                "member_since": "Thành viên từ",
                "transfer_money": "Chuyển tiền",
                "add_wallet": "Nạp ví",
                "view_bills": "Xem hóa đơn",
                "create_savings": "Tạo tiết kiệm",
                "priority_support": "Hỗ trợ ưu tiên",
                "high_limits": "Hạn mức chuyển tiền cao",
                "unlimited_limits": "Hạn mức không giới hạn",
                "standard_limits": "Hạn mức tiêu chuẩn",
                "digital_support": "Hỗ trợ kỹ thuật 24/7",
                "elite_support": "Hỗ trợ Elite 24/7",
                "no_alerts": "Không có thông báo mới.",
                "no_savings": "Chưa có mục tiêu tiết kiệm.",
                "download_qr": "Tải mã QR",
                "upload_qr": "Quét mã QR (Tải lên)",
                "select_qr": "Chọn ảnh QR từ thiết bị",
                "qr_decoded": "Giải mã QR thành công",
                "qr_invalid": "Mã QR này không chứa thông tin thanh toán hợp lệ.",
                "qr_error": "Không thể đọc mã QR thanh toán.",
                "login": "Đăng nhập",
                "register": "Đăng ký",
                "create_account": "Tạo tài khoản",
                "password": "Mật khẩu",
                "remember_me": "Ghi nhớ tôi",
                "forgot_password": "Quên mật khẩu?",
                "access_premium": "Truy cập tài khoản cao cấp của bạn",
                "modern_platform": "Nền tảng ngân hàng số hiện đại",
                "login_successful": "Đăng nhập thành công",
                "invalid_credentials": "Tên đăng nhập hoặc mật khẩu không đúng.",
                "required_fields": "Vui lòng nhập đầy đủ thông tin."
            }
        }
        self._initialized = True

    def set_language(self, lang):
        if lang in self.translations and lang != self.current_language:
            self.current_language = lang
            self.language_changed.emit(lang)

    def get_text(self, key):
        return self.translations[self.current_language].get(key, key)
