from PyQt6.QtCore import QObject, pyqtSignal

class LanguageManager(QObject):
    language_changed = pyqtSignal(str)
    _instance = None

    def __new__(cls):
        if cls._instance is None:
            cls._instance = super(LanguageManager, cls).__new__(cls)
            cls._instance._initialized = False
        return cls._instance

    def __init__(self):
        if self._initialized: return
        super().__init__()
        self.current_language = "en"
        self.translations = {
            "en": {
                "dashboard": "Dashboard",
                "account": "Account Details",
                "wallet": "Wallet",
                "transfer": "Money Transfer",
                "notifications": "Notifications",
                "settings": "Settings",
                "savings": "Savings",
                "savings_dashboard": "Savings Dashboard",
                "new_plan": "New Plan",
                "create_savings_plan": "Create Savings Plan",
                "new_savings_plan": "New Savings Plan",
                "plan_name": "Plan Name",
                "target_amount_placeholder": "Target Amount (VND)",
                "create_plan": "Create Plan",
                "current_balance": "Current Balance",
                "target_amount": "Target Amount",
                "interest_rate": "Interest Rate",
                "maturity_date": "Maturity Date",
                "savings_history": "Savings History",
                "savings_growth": "Savings Growth",
                "active_plans": "Active Plans",
                "total_saved": "Total Saved",
                "monthly_interest": "Est. Monthly Interest",
                "deposit": "Deposit",
                "withdraw": "Withdraw",
                "logout": "Logout",
                "welcome_back": "Welcome back,",
                "manage_finances": "Manage your finances securely with Đăng Khoa Bank",
                "total_balance": "Total Balance",
                "monthly_income": "Monthly Income",
                "monthly_expense": "Monthly Expense",
                "total_savings": "Total Savings",
                "recent_transactions": "Recent Transactions",
                "quick_actions": "Quick Actions",
                "savings_progress": "Savings Progress",
                "virtual_cards": "Virtual Banking Cards",
                "available_balance": "Available Balance",
                "payment_qr": "Personal Payment QR",
                "trans_history": "Wallet Transaction History",
                "outgoing_trans": "Recent Outgoing Transfers",
                "membership": "Customer Membership",
                "benefits": "Member Benefits:",
                "banking_info": "Banking Information",
                "personal_info": "Personal Information",
                "edit_profile": "Edit Profile",
                "full_name": "Full Name",
                "username": "Username",
                "phone": "Phone Number",
                "cccd": "CCCD / Citizen ID",
                "email": "Email Address",
                "appearance": "Appearance",
                "theme_mode": "Theme Mode",
                "dark_mode": "Dark Mode",
                "light_mode": "Light Mode",
                "language": "Language",
                "account_settings": "Account",
                "change_password": "Change Password",
                "phone_payment_id": "Phone Payment ID",
                "acc_number": "Account Number",
                "bank_name": "Bank Name",
                "branch": "Branch",
                "member_since": "Member Since",
                "transfer_money": "Transfer Money",
                "add_wallet": "Add Wallet",
                "view_bills": "View Bills",
                "create_savings": "Create Savings",
                "priority_support": "Priority Support",
                "high_limits": "High Transfer Limits",
                "unlimited_limits": "Unlimited Limits",
                "standard_limits": "Standard Limits",
                "digital_support": "24/7 Digital Support",
                "elite_support": "Priority 24/7 Elite Support",
                "no_alerts": "No recent alerts.",
                "no_savings": "No active saving goals.",
                "download_qr": "Download Payment QR",
                "upload_qr": "Upload Payment QR",
                "select_qr": "Select QR Image from Device",
                "qr_decoded": "QR Decoded Successfully",
                "qr_invalid": "This QR code does not contain valid payment information.",
                "qr_error": "Unable to read payment QR.",
                "login": "Login",
                "register": "Register",
                "create_account": "Create Account",
                "password": "Password",
                "remember_me": "Remember Me",
                "forgot_password": "Forgot Password?",
                "access_premium": "Access your premium account",
                "modern_platform": "Modern Digital Banking Platform",
                "login_successful": "Login successful",
                "invalid_credentials": "Invalid username or password.",
                "required_fields": "Please enter all required fields.",
                "admin_dashboard": "Dashboard",
                "admin_users": "Users",
                "admin_transactions": "Transactions",
                "admin_settings": "Security Center",
                "admin_analytics": "Analytics",
                "admin_reports": "Reports",
                "admin_security": "Security",
                "admin_overview": "System Overview",
                "admin_total_users": "Total Users",
                "admin_total_balance": "Total Balance",
                "admin_today_transactions": "Today's Transactions",
                "admin_active_accounts": "Active Accounts",
                "admin_recent_users": "Recent Users",
                "admin_recent_transactions": "Recent Transactions",
                "admin_users_management": "Users Management",
                "admin_transactions_management": "Transactions Management",
                "admin_search_users": "Search users...",
                "admin_search_transactions": "Search transactions...",
                "admin_search_placeholder": "Search users, transactions...",
                "admin_refresh": "Refresh",
                "admin_sender": "Sender",
                "admin_receiver": "Receiver",
                "admin_amount": "Amount",
                "admin_date": "Date",
                "admin_system": "System",
                "admin_clear_logs": "Clear Logs",
                "admin_backup_database": "Backup Database",
                "admin_header_subtitle": "Admin Control Center",
                "admin_user_details": "User Details",
                "admin_select_user": "Select a user from the table to view details",
                "admin_freeze": "Freeze",
                "admin_unfreeze": "Unfreeze",
                "admin_suspend": "Suspend",
                "admin_set_tier": "Set Tier",
                "admin_confirm_freeze_title": "Freeze Account",
                "admin_confirm_freeze": "Are you sure you want to freeze {user}'s account? They will not be able to transfer money.",
                "admin_confirm_unfreeze_title": "Unfreeze Account",
                "admin_confirm_unfreeze": "Are you sure you want to unfreeze {user}'s account?",
                "admin_confirm_suspend_title": "Suspend Account",
                "admin_confirm_suspend": "Are you sure you want to suspend {user}'s account? They will be blocked from logging in.",
                "admin_confirm_tier_title": "Change Tier",
                "admin_confirm_tier": "Change {user}'s tier to {tier}?",
                "admin_last_login": "Last Login",
                "admin_created_at": "Created At",
                "admin_no_users_found": "No users found.",
                "admin_account_frozen_warning": "Your account is temporarily frozen.",
                "admin_account_suspended_warning": "Your account has been suspended.",
                "admin_txn_details": "Transaction Details",
                "admin_select_txn": "Select a transaction from the table to view details",
                "admin_mark_safe": "Mark Safe",
                "admin_flag_txn": "Flag",
                "admin_block_txn": "Block",
                "admin_set_reviewing": "Reviewing",
                "admin_note": "Note",
                "admin_orig_status": "Original Status",
                "admin_no_txn_found": "No transactions found.",
                "admin_suspicious_alerts": "Suspicious Activity Alerts",
                "admin_flagged_txns": "flagged transactions",
                "admin_high_risk_txns": "high risk transactions",
                "admin_monthly_volume": "Monthly Volume",
                "admin_flagged_count": "Flagged Transactions",
                "admin_analytics_charts": "Analytics Overview",
                "admin_daily_transactions": "Daily Transactions (7 Days)",
                "admin_tier_distribution": "Tier Distribution",
                "admin_user_growth": "User Growth (7 Days)",
                "admin_risk_distribution": "Risk Distribution",
                "admin_fraud_overview": "Fraud Monitoring Overview",
                "admin_blocked_transfers": "Blocked Transfers",
                "admin_suspicious_users": "Suspicious Users",
                "admin_system_health": "System Health",
                "admin_db_status": "Database Status",
                "admin_total_records": "Total Records",
                "admin_recent_activity": "Recent Activity",
                "admin_no_activity": "No recent activity.",
                "admin_security_overview": "Security Overview",
                "admin_security_alerts": "Security Alerts",
                "admin_active_sessions": "Active Sessions",
                "admin_login_history": "Login History",
                "admin_activity_logs": "Admin Activity Logs",
                "admin_end_session": "End Session",
                "admin_end_all": "End All",
                "admin_no_alerts": "No suspicious activity detected.",
                "admin_no_sessions": "No active sessions found.",
                "admin_no_login_history": "No login history available.",
                "admin_no_activity_logs": "No administrative logs available.",
                "admin_security_center_title": "Security Operations Center",
                "admin_time": "Time",
                "admin_status": "Status",
                "admin_device": "Device",
                "admin_location": "Location",
                "admin_admin_col": "Admin",
                "admin_action_col": "Action",
                "admin_target_col": "Target",
                "admin_navigation": "NAVIGATION",
                "admin_coming_soon": "COMING SOON",
                "admin_system_settings": "System Settings",
                "admin_system_announcements": "System Announcements",
                "admin_no_announcements": "No announcements available.",
                "admin_create_announcement": "Create Announcement",
                "admin_ann_title_placeholder": "Enter announcement title...",
                "admin_ann_msg_placeholder": "Enter announcement message...",
                "admin_ann_clear": "Clear Form",
                "admin_ann_send": "Send Announcement",
                "admin_notification_history": "Notification History",
                "admin_no_ann_history": "No announcement history available.",
                "admin_system_tools_title": "System Tools & Database Management",
                "admin_backup_title": "Local SQLite Backup",
                "admin_last_backup": "Last Backup",
                "admin_db_size": "Database Size",
                "admin_backup_count": "Backup Count",
                "admin_btn_create_backup": "Create Backup",
                "admin_btn_restore_backup": "Restore Backup",
                "admin_btn_open_folder": "Open Backup Folder",
                "admin_tool_cleanup_title": "System Cleanup",
                "admin_tool_cleanup_desc": "Clear old temp files, expired sessions, and verification TXTs.",
                "admin_btn_cleanup": "Run Cleanup",
                "admin_tool_export_title": "Export Audit Logs",
                "admin_tool_export_desc": "Export security logs and transaction history to CSV/JSON.",
                "admin_btn_export": "Export Logs",
                "admin_tool_maintenance_title": "Emergency Maintenance",
                "admin_tool_maintenance_desc": "Disable user logins and transfers temporarily.",
                "admin_maintenance_active": "MAINTENANCE MODE ACTIVE. Users cannot log in.",
                "admin_btn_toggle_maintenance": "Toggle Mode",
                
                "admin_reports": "Reports",
                "admin_reports_header_title": "Enterprise Financial Reports",
                "admin_reports_header_desc": "Advanced banking analytics and export tools are currently under development.",
                "admin_reports_hero_desc": "Next-generation banking reporting tools are being prepared.",
                "admin_report_modules": "Report Modules",
                "admin_export_options": "Export Options",
                "admin_future_roadmap": "Future Features Roadmap",
                "admin_rep_txn_title": "Transaction Reports",
                "admin_rep_txn_desc": "Detailed flow analysis and settlement logs.",
                "admin_rep_cust_title": "Customer Reports",
                "admin_rep_cust_desc": "Growth, tier distribution, and engagement metrics.",
                "admin_rep_fraud_title": "Fraud Reports",
                "admin_rep_fraud_desc": "Suspicious activity deep dives and security audits.",
                "admin_rep_finance_title": "Financial Statements",
                "admin_rep_finance_desc": "Monthly revenue, liabilities, and assets summary.",
                "admin_status_in_dev": "IN DEVELOPMENT",
                "admin_status_planned": "PLANNED",
                "admin_status_enterprise": "ENTERPRISE",
                "admin_preview": "Preview",
                "admin_feature_future": "Feature available in future update.",
                "admin_btn_export_pdf": "Export PDF",
                "admin_btn_export_excel": "Export Excel",
                "admin_btn_generate_report": "Generate Report",
                "admin_btn_schedule_report": "Schedule Report",
                "admin_rdmp_ai_title": "AI Fraud Reports",
                "admin_rdmp_ai_desc": "Machine learning driven risk analysis.",
                "admin_rdmp_auto_title": "Automated Financial Summaries",
                "admin_rdmp_auto_desc": "Weekly emailed PDFs for management.",
                "admin_rdmp_smart_title": "Smart Analytics",
                "admin_rdmp_smart_desc": "Predictive user growth metrics.",
                "admin_rdmp_cloud_title": "Cloud Backup Reports",
                "admin_rdmp_cloud_desc": "Direct export to secure cloud storage.",
                
                "enter_security_pin": "Enter Security PIN",
                "pin_desc": "Please enter your 6-digit security PIN to confirm this action.",
                "cancel": "Cancel",
                "confirm": "Confirm"
            },
            "vi": {
                "dashboard": "Bảng điều khiển",
                "account": "Thông tin tài khoản",
                "wallet": "Ví của tôi",
                "transfer": "Chuyển tiền",
                "notifications": "Thông báo",
                "settings": "Cài đặt",
                "savings": "Tiết kiệm",
                "savings_dashboard": "Quản lý Tiết kiệm",
                "new_plan": "Kế hoạch mới",
                "create_savings_plan": "Tạo gói tiết kiệm",
                "new_savings_plan": "Gói tiết kiệm mới",
                "plan_name": "Tên kế hoạch",
                "target_amount_placeholder": "Số tiền mục tiêu (VND)",
                "create_plan": "Tạo kế hoạch",
                "current_balance": "Số dư hiện tại",
                "target_amount": "Số tiền mục tiêu",
                "interest_rate": "Lãi suất",
                "maturity_date": "Ngày đáo hạn",
                "savings_history": "Lịch sử tiết kiệm",
                "savings_growth": "Tăng trưởng tiết kiệm",
                "active_plans": "Gói đang hoạt động",
                "total_saved": "Tổng tiền tiết kiệm",
                "monthly_interest": "Lãi dự kiến hàng tháng",
                "deposit": "Gửi tiền",
                "withdraw": "Rút tiền",
                "logout": "Đăng xuất",
                "welcome_back": "Chào mừng trở lại,",
                "manage_finances": "Quản lý tài chính an toàn với Đăng Khoa Bank",
                "total_balance": "Tổng số dư",
                "monthly_income": "Thu nhập tháng",
                "monthly_expense": "Chi tiêu tháng",
                "total_savings": "Tổng tiết kiệm",
                "recent_transactions": "Giao dịch gần đây",
                "quick_actions": "Thao tác nhanh",
                "savings_progress": "Tiến độ tiết kiệm",
                "virtual_cards": "Thẻ ngân hàng ảo",
                "available_balance": "Số dư khả dụng",
                "payment_qr": "Mã QR thanh toán",
                "trans_history": "Lịch sử giao dịch ví",
                "outgoing_trans": "Giao dịch chuyển tiền gần đây",
                "membership": "Hạng thành viên",
                "benefits": "Quyền lợi thành viên:",
                "banking_info": "Thông tin ngân hàng",
                "personal_info": "Thông tin cá nhân",
                "edit_profile": "Chỉnh sửa hồ sơ",
                "full_name": "Họ và tên",
                "username": "Tên đăng nhập",
                "phone": "Số điện thoại",
                "cccd": "CCCD / CMND",
                "email": "Địa chỉ Email",
                "appearance": "Giao diện",
                "theme_mode": "Chế độ nền",
                "dark_mode": "Nền tối",
                "light_mode": "Nền sáng",
                "language": "Ngôn ngữ",
                "account_settings": "Tài khoản",
                "change_password": "Đổi mật khẩu",
                "phone_payment_id": "ID thanh toán SĐT",
                "acc_number": "Số tài khoản",
                "bank_name": "Ngân hàng",
                "branch": "Chi nhánh",
                "member_since": "Thành viên từ",
                "transfer_money": "Chuyển tiền",
                "add_wallet": "Nạp ví",
                "view_bills": "Xem hóa đơn",
                "create_savings": "Tạo tiết kiệm",
                "priority_support": "Hỗ trợ ưu tiên",
                "high_limits": "Hạn mức chuyển tiền cao",
                "unlimited_limits": "Hạn mức không giới hạn",
                "standard_limits": "Hạn mức tiêu chuẩn",
                "digital_support": "Hỗ trợ kỹ thuật 24/7",
                "elite_support": "Hỗ trợ Elite 24/7",
                "no_alerts": "Không có thông báo mới.",
                "no_savings": "Chưa có mục tiêu tiết kiệm.",
                "download_qr": "Tải mã QR",
                "upload_qr": "Quét mã QR (Tải lên)",
                "select_qr": "Chọn ảnh QR từ thiết bị",
                "qr_decoded": "Giải mã QR thành công",
                "qr_invalid": "Mã QR này không chứa thông tin thanh toán hợp lệ.",
                "qr_error": "Không thể đọc mã QR thanh toán.",
                "login": "Đăng nhập",
                "register": "Đăng ký",
                "create_account": "Tạo tài khoản",
                "password": "Mật khẩu",
                "remember_me": "Ghi nhớ tôi",
                "forgot_password": "Quên mật khẩu?",
                "access_premium": "Truy cập tài khoản cao cấp của bạn",
                "modern_platform": "Nền tảng ngân hàng số hiện đại",
                "login_successful": "Đăng nhập thành công",
                "invalid_credentials": "Tên đăng nhập hoặc mật khẩu không đúng.",
                "required_fields": "Vui lòng nhập đầy đủ thông tin.",
                "admin_dashboard": "Bảng điều khiển",
                "admin_users": "Người dùng",
                "admin_transactions": "Giao dịch",
                "admin_settings": "Trung tâm Bảo mật",
                "admin_analytics": "Phân tích",
                "admin_reports": "Báo cáo",
                "admin_security": "Bảo mật",
                "admin_overview": "Tổng quan hệ thống",
                "admin_total_users": "Tổng người dùng",
                "admin_total_balance": "Tổng số dư",
                "admin_today_transactions": "Giao dịch hôm nay",
                "admin_active_accounts": "Tài khoản hoạt động",
                "admin_recent_users": "Người dùng gần đây",
                "admin_recent_transactions": "Giao dịch gần đây",
                "admin_users_management": "Quản lý người dùng",
                "admin_transactions_management": "Quản lý giao dịch",
                "admin_search_users": "Tìm kiếm người dùng...",
                "admin_search_transactions": "Tìm kiếm giao dịch...",
                "admin_search_placeholder": "Tìm kiếm người dùng, giao dịch...",
                "admin_refresh": "Làm mới",
                "admin_sender": "Người gửi",
                "admin_receiver": "Người nhận",
                "admin_amount": "Số tiền",
                "admin_date": "Ngày",
                "admin_system": "Hệ thống",
                "admin_clear_logs": "Xóa nhật ký",
                "admin_backup_database": "Sao lưu cơ sở dữ liệu",
                "admin_header_subtitle": "Trung tâm quản trị",
                "admin_user_details": "Chi tiết người dùng",
                "admin_select_user": "Chọn người dùng từ bảng để xem chi tiết",
                "admin_freeze": "Đóng băng",
                "admin_unfreeze": "Mở đóng băng",
                "admin_suspend": "Đình chỉ",
                "admin_set_tier": "Đặt hạng",
                "admin_confirm_freeze_title": "Đóng băng tài khoản",
                "admin_confirm_freeze": "Bạn có chắc muốn đóng băng tài khoản {user}? Họ sẽ không thể chuyển tiền.",
                "admin_confirm_unfreeze_title": "Mở đóng băng tài khoản",
                "admin_confirm_unfreeze": "Bạn có chắc muốn mở đóng băng tài khoản {user}?",
                "admin_confirm_suspend_title": "Đình chỉ tài khoản",
                "admin_confirm_suspend": "Bạn có chắc muốn đình chỉ tài khoản {user}? Họ sẽ bị chặn đăng nhập.",
                "admin_confirm_tier_title": "Thay đổi hạng",
                "admin_confirm_tier": "Thay đổi hạng của {user} thành {tier}?",
                "admin_last_login": "Đăng nhập cuối",
                "admin_created_at": "Ngày tạo",
                "admin_no_users_found": "Không tìm thấy người dùng.",
                "admin_account_frozen_warning": "Tài khoản của bạn đã bị đóng băng tạm thời.",
                "admin_account_suspended_warning": "Tài khoản của bạn đã bị đình chỉ.",
                "admin_txn_details": "Chi tiết giao dịch",
                "admin_select_txn": "Chọn giao dịch từ bảng để xem chi tiết",
                "admin_mark_safe": "Đánh dấu an toàn",
                "admin_flag_txn": "Ghi cờ",
                "admin_block_txn": "Chặn",
                "admin_set_reviewing": "Đang xem xét",
                "admin_note": "Ghi chú",
                "admin_orig_status": "Trạng thái gốc",
                "admin_no_txn_found": "Không tìm thấy giao dịch.",
                "admin_suspicious_alerts": "Cảnh báo hoạt động đáng ngờ",
                "admin_flagged_txns": "giao dịch bị ghi cờ",
                "admin_high_risk_txns": "giao dịch rủi ro cao",
                "admin_monthly_volume": "Khối lượng tháng",
                "admin_flagged_count": "Giao dịch bị ghi cờ",
                "admin_analytics_charts": "Tổng quan phân tích",
                "admin_daily_transactions": "Giao dịch hàng ngày (7 ngày)",
                "admin_tier_distribution": "Phân bổ hạng",
                "admin_user_growth": "Tăng trưởng người dùng (7 ngày)",
                "admin_risk_distribution": "Phân bổ rủi ro",
                "admin_fraud_overview": "Tổng quan giám sát gian lận",
                "admin_blocked_transfers": "Chuyển khoản bị chặn",
                "admin_suspicious_users": "Người dùng đáng ngờ",
                "admin_system_health": "Tình trạng hệ thống",
                "admin_db_status": "Trạng thái cơ sở dữ liệu",
                "admin_total_records": "Tổng bản ghi",
                "admin_recent_activity": "Hoạt động gần đây",
                "admin_no_activity": "Không có hoạt động gần đây.",
                "admin_security_overview": "Tổng quan Bảo mật",
                "admin_security_alerts": "Cảnh báo Bảo mật",
                "admin_active_sessions": "Phiên hoạt động",
                "admin_login_history": "Lịch sử Đăng nhập",
                "admin_activity_logs": "Nhật ký Quản trị",
                "admin_end_session": "Kết thúc Phiên",
                "admin_end_all": "Kết thúc Tất cả",
                "admin_no_alerts": "Không phát hiện hoạt động đáng ngờ.",
                "admin_no_sessions": "Không tìm thấy phiên hoạt động nào.",
                "admin_no_login_history": "Không có lịch sử đăng nhập.",
                "admin_no_activity_logs": "Không có nhật ký quản trị.",
                "admin_security_center_title": "Trung tâm Điều hành An ninh",
                "admin_time": "Thời gian",
                "admin_status": "Trạng thái",
                "admin_device": "Thiết bị",
                "admin_location": "Vị trí",
                "admin_admin_col": "Quản trị viên",
                "admin_action_col": "Hành động",
                "admin_target_col": "Đối tượng",
                "admin_navigation": "ĐIỀU HƯỚNG",
                "admin_coming_soon": "SẮP RA MẮT",
                "admin_system_settings": "Cài đặt Hệ thống",
                "admin_system_announcements": "Thông báo Hệ thống",
                "admin_no_announcements": "Không có thông báo nào.",
                "admin_create_announcement": "Tạo Thông báo",
                "admin_ann_title_placeholder": "Nhập tiêu đề thông báo...",
                "admin_ann_msg_placeholder": "Nhập nội dung thông báo...",
                "admin_ann_clear": "Xóa Form",
                "admin_ann_send": "Gửi Thông báo",
                "admin_notification_history": "Lịch sử Thông báo",
                "admin_no_ann_history": "Không có lịch sử thông báo.",
                "admin_system_tools_title": "Công cụ Hệ thống & Quản lý CSDL",
                "admin_backup_title": "Sao lưu SQLite Cục bộ",
                "admin_last_backup": "Sao lưu gần nhất",
                "admin_db_size": "Kích thước CSDL",
                "admin_backup_count": "Số lượng bản sao",
                "admin_btn_create_backup": "Tạo Sao lưu",
                "admin_btn_restore_backup": "Khôi phục",
                "admin_btn_open_folder": "Mở Thư mục",
                "admin_tool_cleanup_title": "Dọn dẹp Hệ thống",
                "admin_tool_cleanup_desc": "Xóa file tạm, phiên hết hạn và TXT xác minh.",
                "admin_btn_cleanup": "Chạy Dọn dẹp",
                "admin_tool_export_title": "Xuất Nhật ký",
                "admin_tool_export_desc": "Xuất nhật ký bảo mật và giao dịch (CSV/JSON).",
                "admin_btn_export": "Xuất Log",
                "admin_tool_maintenance_title": "Bảo trì Khẩn cấp",
                "admin_tool_maintenance_desc": "Tạm dừng đăng nhập và chuyển khoản của người dùng.",
                "admin_maintenance_active": "ĐANG BẢO TRÌ. Người dùng không thể đăng nhập.",
                "admin_btn_toggle_maintenance": "Chuyển Đổi",
                
                "admin_reports": "Báo cáo",
                "admin_reports_header_title": "Báo cáo Tài chính Doanh nghiệp",
                "admin_reports_header_desc": "Công cụ phân tích và xuất dữ liệu nâng cao đang được phát triển.",
                "admin_reports_hero_desc": "Công cụ báo cáo ngân hàng thế hệ mới đang được chuẩn bị.",
                "admin_report_modules": "Module Báo cáo",
                "admin_export_options": "Tùy chọn Xuất",
                "admin_future_roadmap": "Lộ trình Tính năng",
                "admin_rep_txn_title": "Báo cáo Giao dịch",
                "admin_rep_txn_desc": "Phân tích dòng tiền và nhật ký đối soát chi tiết.",
                "admin_rep_cust_title": "Báo cáo Khách hàng",
                "admin_rep_cust_desc": "Chỉ số tăng trưởng, phân bổ hạng và mức độ tương tác.",
                "admin_rep_fraud_title": "Báo cáo Gian lận",
                "admin_rep_fraud_desc": "Phân tích chuyên sâu hoạt động đáng ngờ và kiểm toán.",
                "admin_rep_finance_title": "Báo cáo Tài chính",
                "admin_rep_finance_desc": "Tóm tắt doanh thu, tài sản và nghĩa vụ nợ hàng tháng.",
                "admin_status_in_dev": "ĐANG PHÁT TRIỂN",
                "admin_status_planned": "ĐÃ LÊN KẾ HOẠCH",
                "admin_status_enterprise": "ENTERPRISE",
                "admin_preview": "Xem trước",
                "admin_feature_future": "Tính năng sẽ có trong bản cập nhật tương lai.",
                "admin_btn_export_pdf": "Xuất PDF",
                "admin_btn_export_excel": "Xuất Excel",
                "admin_btn_generate_report": "Tạo Báo cáo",
                "admin_btn_schedule_report": "Lên lịch Báo cáo",
                "admin_rdmp_ai_title": "Báo cáo Gian lận AI",
                "admin_rdmp_ai_desc": "Phân tích rủi ro dựa trên học máy.",
                "admin_rdmp_auto_title": "Tóm tắt Tài chính Tự động",
                "admin_rdmp_auto_desc": "Gửi PDF tự động hàng tuần cho ban quản trị.",
                "admin_rdmp_smart_title": "Phân tích Thông minh",
                "admin_rdmp_smart_desc": "Chỉ số dự báo tăng trưởng người dùng.",
                "admin_rdmp_cloud_title": "Báo cáo Lưu trữ Đám mây",
                "admin_rdmp_cloud_desc": "Xuất trực tiếp tới bộ nhớ đám mây an toàn."
            }
        }
        self._initialized = True

    def set_language(self, lang):
        if lang in self.translations and lang != self.current_language:
            self.current_language = lang
            self.language_changed.emit(lang)

    def get_text(self, key):
        return self.translations[self.current_language].get(key, key)
